---
extends: existence
level: suggestion
link: https://github.com/riscv/docs-dev-guide
message: "Do not overuse beginning sentences with '%s'."
scope: paragraph
# source: https://github.com/redhat-documentation/vale-at-red-hat/tree/main/.vale/styles/RedHat/Conjunctions.yml
action:
  name: remove
tokens:
  - ^And
  - ^But
  - ^Or
  - ^So
