---
extends: existence
level: suggestion
link: https://github.com/riscv/docs-dev-guide
message: "Avoid the ellipsis (...) except to indicate omitted words."
nonword: true
# source: "IBM - Ellipses, p.49"
action:
  name: remove
tokens:
  - '\.\.\.'
  - "…"
