---
extends: substitution
ignorecase: true
level: warning
link: https://lf-riscv.atlassian.net/wiki/spaces/TAXX/pages/565510188/Friendly+Terminology
message: "Use %s rather than '%s'."
action:
  name: replace
swap:
  blacklist: blocklist
  master(?! broker): primary|source|initiator|requester|controller|host|director|supplier
  slave(?! broker): secondary|replica|responder|device|worker|proxy|performer|consumer|child
  whitelist: allowlist
  
