---
extends: existence
scope: raw
level: error
nonword: true
link: https://github.com/riscv/docs-dev-guide
message: "Do not commit Git merge conflict markers in source code."
action:
  name: remove
tokens:
  - '^<{7}\s.*$'
  - '^={7}$'
  - '^>{7}\s.*$'
