---
extends: repetition
message: "'%s' is repeated."
level: warning
link: https://github.com/riscv/docs-dev-guide
ignorecase: false
alpha: true
action:
  name: edit
  params:
    - regex
    - '(\w+)(\s\w+)' # pattern
    - "$1" # replace
tokens:
  - '[^\s\.]+'
  - '[^\s]+'
