---
extends: existence
ignorecase: true
level: warning
link: https://github.com/riscv/docs-dev-guide
message: "Use either 'or' or 'and' in '%s'"
# source: "IBM - Slashes, p. 68"
scope:
  - sentence
  - heading
tokens:
  - '(?<!/)\w+/\w+'
exceptions:
  - '\d{1,4}\/\d{1,4}'
  - "0/"
  - "[Ii]nput/[Oo]utput"
  - "C/C"
  - "CI/CD"
  - "client/server"
  - "I/O"
  - "N/A"
  - "read/write"
  - "SSL/TLS"
  - "TCP/IP"
  - "upstream/downstream"
  - "[Kk]ey/value"
  
