#file: noinspection IncorrectFormatting
---
extends: spelling
level: warning
link: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/spelling/
message: "Verify the word '%s'. It is not in the American English spelling dictionary used by Vale."
# A "filter" is a case-sensitive regular expression specifying words to ignore during spell checking.
# Spelling rule applies to individual words
# There is no need to add plural forms (s?) to the regex
filters:
  - "[aA]llowlist"
  - "[bB]itwise"
  - "[bB]oolean"
  - "[cC]acheability"
  - "[cC]omparand"
  - "[dD]atapath"
  - "[dD]oubleword"
  - "[eE]ndian"
  - "FPGA"
  - "[gG]igapages"
  - "[hH]alfword"
  - "IEC"
  - "IEEE"
  - "[iI]mmediates"
  - "[mM]acrocode"
  - "[mM]anycode"
  - "[mM]egapages"
  - "[mM]multiprogrammed"
  - "[mM]ultithreaded"
  - "[mM]multithreading"
  - "[mM]icroarchitecture"
  - "[mM]icroarchitectural"
  - "[mM]icrocontroller"
  - "[mM]illicode"
  - "[pP]etapages"
  - "[pP]refetches"
  - "[pP]seudocode"
  - "[pP]seudoinstruction"
  - "[rR]estorability"
  - "RISC"
  - "RISC-V"
  - "[sS]box"
  - "[sS]emihosting"
  - "SOAR"
  - "SPUR"
  - "[sS]ubblock"
  - "[sS]ubword"
  - "[sS]uperpages"
  - "[tT]erapages"
  - "TLB shootdown"
  - "[uU]ninferrable"
  - "[vV]irtualize"
  - "[vV]irtualization"
  




