#file: noinspection IncorrectFormatting
---
extends: spelling
level: warning
link: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/spelling/
message: "Verify the word '%s'. It is not in the American English spelling dictionary used by Vale."
# A "filter" is a case-sensitive regular expression specifying words to ignore during spell checking.
# Spelling rule applies to individual words
# There is no need to add plural forms (s?) to the regex
filters:
  - "[aA]llowlist"
  - "AMO"
  - "[aA]rchitected"
  - "[bB]itwise"
  - "[bB]oolean"
  - "[bB]reakpoint"
  - "[cC]acheable"
  - "[cC]acheability"
  - "[cC]acheless"
  - "[cC]anonicalize"
  - "[cC]anonicalizing"
  - "[cC]arryless"
  - "[cC]iphertext"
  - "CMO"
  - "[cC]omparand"
  - "[cC]oroutine"
  - "[cC]rypto"
  - "CSR"
  - "CSRs"
  - "[dD]atapath"
  - "[dD]eallocate"
  - "[dD]elegatable"
  - "[dD]enormalize"
  - "[dD]enormalized"
  - "[dD]iscoverability"
  - "[dD]oubleword"
  - "[eE]mulable"
  - "[eE]ndian"
  - "[eE]nqueue"
  - "[eE]xascale"
  - "[fF]anout"
  - "[fF]etchable"
  - "FPGA"
  - "[gG]igapages"
  - "GPA"  
  - "[gG]ranularities"
  - "[hH]alfword"
  - "[hH]ardwire"
  - "[iI]dempotency"
  - "IEC"
  - "IEEE"
  - "[iI]mmediates"
  - "[iI]nteroperate"
  - "[iI]nterprocessor"
  - "[iI]nvalidation"
  - "ISA"
  - "ISAs"
  - "[lL]ivelock"
  - "[mM]acrocode"
  - "[mM]anycore"
  - "[mM]askable"
  - "[mM]egapages"
  - "[mM]iddleware"
  - "[mM]itigation"
  - "[mM]isdescribe"
  - "[mM]isdescribed"
  - "[mM]ispredict"
  - "[mM]ulticode"
  - "[mM]ulticomputer"
  - "[mM]ulticore"
  - "[mM]ultiprogrammed"
  - "[mM]ultithreaded"
  - "[mM]ultithreading"
  - "[mM]icroarchitecture"
  - "[mM]icroarchitectural"
  - "[mM]icrocontroller"
  - "[mM]illicode"
  - "[nN]ondecreasing"
  - "[nN]ullary" 
  - "PMA"
  - "[pP]erformant"
  - "[pP]etapages"
  - "[pP]ipelining"
  - "[pP]laintext"
  - "[pP]luggable"
  - "[pP]refetch"  
  - "[pP]refetches"
  - "[pP]seudocode"
  - "[pP]seudoinstruction"
  - "[qQ]uadword"
  - "[rR]eassociate"
  - "[rR]edefinable"
  - "[rR]epurpose"
  - "[rR]estorability"
  - "RISC"
  - "RISC-V"
  - "[rR]untime"
  - "[sS]andboxing"
  - "[sS]box"
  - "[sS]emihosting"
  - "[sS]ignificand"
  - "SM"
  - "Smcdeleg"
  - "Smcntrpmf"
  - "Smcsrind"
  - "Smhpm"
  - "Smpmp"
  - "Smstateen"
  - "SOAR"
  - "SPUR"
  - "Sscofpmf"
  - "Sscsrind"
  - "[sS]ubarray"
  - "[sS]ubblock"
  - "[sS]ubfield"
  - "[sS]ubscripted"
  - "[sS]ubword"
  - "[sS]uperpage"
  - "[sS]uperset"
  - "Sv32"
  - "Sv39"
  - "Sv48"
  - "Sv57"
  - "Svadu"
  - "Svinval"
  - "Svnapot"
  - "Svpbmt"
  - "Svvptc"
  - "[sS]wappable"
  - "[tT]erapages"
  - "TLB shootdown"
  - "[uU]ninferrable"
  - "[uU]ncached"
  - "[uU]ndercount"
  - "[uU]nderflow"
  - "[uU]npropagate"
  - "[uU]npropagated"
  - "[uU]nresumable"
  - "[uU]ntag"
  - "[uU]ntaken"
  - "[vV]ectorize"
  - "Verilog"
  - "[vV]irtualize"
  - "[vV]irtualization"
  - "[wW]atchpoint"
  - "Zabha"
  - "Zacas"
  - "Zba"
  - "Zbb"
  - "Zbc"
  - "Zbkb"
  - "Zbkc"
  - "Zbkx"
  - "Zbs"
  - "Zca"
  - "Zcb"
  - "Zcd"
  - "Zcf"
  - "Zcmp"
  - "Zcmt"
  - "Zfa"
  - "Zfbfmin"
  - "Zfh"
  - "Zfhmin"
  - "Zhinx"
  - "Zicbom"
  - "Zicbop"
  - "Zicboz"
  - "Zicfilp"
  - "Zicfiss"
  - "Zicntr"
  - "Zicond"
  - "Zicsr"
  - "Zifencei"
  - "Zihintntl"
  - "Zihintpause"
  - "Zihpm"
  - "Zk"
  - "Zkn"
  - "Zknd"
  - "Zkne"
  - "Zkhd"
  - "Zkr"
  - "Zks"
  - "Zksed"
  - "Zksh"
  - "Zkt"
  - "Zvbb"
  - "Zvbc"
  - "Zve32f"
  - "Zvfbfmin"
  - "Zvfbfwma"
  - "Zvfh"
  - "Zvfhmin"
  - "Zvkb"
  - "Zvkg"
  - "Zvkn"
  - "Zvknc"
  - "Zvkned"
  - "Zvkng"
  - "Zvknha"
  - "Zvknha"
  - "Zvknhb"
  - "Zvknhb"
  - "Zvks"
  - "Zvksc"
  - "Zvksed"
  - "Zvksg"
  - "Zvksh"
  - "Zvkt"

